{{ if eq .Values.tools.enabled true }}
---
{{- if not (lookup "v1" "Secret" $.Values.tools.namespace "keycloak-postgres") }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres
  namespace: {{ .Values.tools.namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  username: keycloakDbUser
  password: {{ randAlphaNum 24 }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-pvc
  namespace: {{ .Values.tools.namespace }}
  labels:
    app: keycloak-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-db
  namespace: {{ .Values.tools.namespace }}
spec:
  serviceName: keycloak-db
  selector:
    matchLabels:
      app: keycloak-db
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: {{ .Values.tools.keycloak.database.image }}
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: keycloak-data
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres
                  key: password
            - name: POSTGRESQL_DATABASE
              value: keycloak
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: {{ .Values.tools.namespace }}
spec:
  selector:
    app: keycloak-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
{{end}}
