apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-exec
  namespace: {{ .Values.tools.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
