apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: set-no-ssl
  namespace: {{ .Values.tools.namespace }}
spec:
  backoffLimit: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - kubectl exec pod/keycloak-0 -- /bin/bash -c "while ! /opt/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE --server http://localhost:8080/ --realm master --user $username --password $password --no-config; do sleep 10; done"
        image: quay.io/rh_integration/ci-toolbox:latest  # kubectl
        name: set-no-ssl
        envFrom:
        - secretRef:
            name: keycloak-initial-admin
        resources: {}
      serviceAccount: keycloak-config
      restartPolicy: OnFailure
status: {}
