{{ if .Values.tools.customMetricsApiserver.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-metrics-apiserver
  name: custom-metrics-apiserver
  namespace: {{ .Values.tools.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: custom-metrics-apiserver
        image: {{ .Values.tools.customMetricsApiserver.image }}
        imagePullPolicy: Always
        args:
        - --secure-port=6443
        - --cert-dir=/var/run/serving-cert
        - --v=10
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /tmp
          name: temp-vol
          readOnly: false
        - mountPath: /var/run/serving-cert
          name: volume-serving-cert
          readOnly: false
      volumes:
      - name: temp-vol
        emptyDir: {}
      - name: volume-serving-cert
        emptyDir: {}
{{end}}