{{ if .Values.tools.customMetricsApiserver.enable }}
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver-discovery
  namespace: {{ .Values.tools.namespace }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: custom-metrics-apiserver
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  namespace: {{ .Values.tools.namespace }}
spec:
  ports:
  - name: https
    port: 8080
    targetPort: 8080
  selector:
    app: custom-metrics-apiserver
  type: LoadBalancer
{{end}}