apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuadrant-qe-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Kuadrant QE Root CA"
  secretName: kuadrant-qe-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
    - cert sign
    - crl sign
  issuerRef:
    name: selfsigned-issuer 
    kind: ClusterIssuer
    group: cert-manager.io
