{{- if .Values.kuadrant.extensionsBinaryImage }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plan-policy-manager-role
rules:
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - planpolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - planpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - planpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - ratelimitpolicies
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plan-policy-manager-role-binding
roleRef:
  name: plan-policy-manager-role
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: kuadrant-operator-controller-manager
  namespace: {{ .Values.kuadrant.namespace }}
{{- end }}