{{ if and (.Values.tools.keycloak.enable) (eq .Values.tools.keycloak.keycloakProvider "operator") }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  namespace: {{ .Values.tools.namespace }}
spec:
  channel: {{ .Values.tools.keycloak.operator.channel }}
  installPlanApproval: {{ .Values.tools.keycloak.operator.installPlanApproval }}
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  {{- if eq .Values.tools.keycloak.operator.installPlanApproval "Manual"}}
  startingCSV: {{ .Values.tools.keycloak.operator.startingCSV }}
  {{- end}}
{{end}}
