[allowlist]
description = "Global Allowlist"

paths = [
    # Ignore testing CA
    "charts/kuadrant-instances/templates/cert-manager/ca/tls.key",
    "charts/kuadrant-instances/templates/cert-manager/02-ca.yaml"
]
