{{ if and (.Values.tools.keycloak.enable) (eq .Values.tools.keycloak.keycloakProvider "deployment") }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin
  namespace: {{ .Values.tools.namespace }}
stringData:
  username: "tmp-admin"
  password: {{ randAlphaNum 24 | quote }}
type: Opaque
{{ end }}
