{{ if and (.Values.tools.keycloak.enable) (eq .Values.tools.keycloak.keycloakProvider "operator") }}
kind: Keycloak
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: keycloak
  namespace: {{ .Values.tools.namespace }}
  labels:
    app: sso
spec:
  additionalOptions:
    - name: KC_CACHE
      value: local
  hostname:
    strict: false
  ingress:
    enabled: false
  http:
    httpEnabled: true
    httpPort: 8080
  db:
    vendor: postgres
    host: keycloak-db
    database: keycloak
    port: 5432
    usernameSecret: 
      name: keycloak-postgres
      key: username
    passwordSecret:
      name: keycloak-postgres
      key: password
{{end}}
