{{ if and .Values.tools.vault.enable .Values.tools.vault.installSCC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-anyuid-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: vault
  namespace: {{ .Values.vault.global.namespace }}
{{ end }}
