{{ if eq .Values.tools.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-config
  namespace: {{ .Values.kuadrant.namespace }}
type: Opaque
data:
  # It is redis://redis.tools.svc.cluster.local:6379
  URL: "cmVkaXM6Ly9yZWRpcy50b29scy5zdmMuY2x1c3Rlci5sb2NhbDo2Mzc5"
{{- end }}
