apiVersion: v1
kind: Service
metadata:
  name: keycloak-service-load-balancer
  namespace: {{ .Values.keycloak.namespace }}
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      protocol: TCP
  type: LoadBalancer
