{{ if eq .Values.tools.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: valkey-config
  namespace: {{ .Values.kuadrant.namespace }}
type: Opaque
data:
  # It is redis://valkey.tools.svc.cluster.local:6379
  URL: "cmVkaXM6Ly92YWxrZXkudG9vbHMuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ=="
{{- end }}
