{{ if .Values.tools.spicedb.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spicedb
  namespace: {{ .Values.tools.namespace }}
  labels:
    app: spicedb
spec:
  selector:
    matchLabels:
      app: spicedb
  template:
    metadata:
      labels:
        app: spicedb
    spec:
      containers:
        - name: spicedb
          image: {{ .Values.tools.spicedb.image }}
          args:
            - serve
          env:
            - name: "SPICEDB_LOG_LEVEL"
              value: "debug"
            - name: "SPICEDB_HTTP_ENABLED"
              value: "true"
            - name: "SPICEDB_GRPC_PRESHARED_KEY"
              valueFrom:
                secretKeyRef:
                  name: "spicedb-key"
                  key: "SPICEDB_GRPC_PRESHARED_KEY"
          ports:
            - containerPort: 50051
            - containerPort: 8443
  replicas: 1
{{ end }}
