{{ if .Values.tools.spicedb.enable }}
apiVersion: v1
kind: Service
metadata:
  name: spicedb
  namespace: {{ .Values.tools.namespace }}
  labels:
    app: spicedb
spec:
  selector:
    app: spicedb
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
    - name: http
      port: 8443
      protocol: TCP
  type: LoadBalancer
{{ end }}
