apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  channel: {{ .Values.certManager.operator.channel }}
  installPlanApproval: {{ .Values.certManager.operator.installPlanApproval }}
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.certManager.operator.startingCSV}}
