apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: post-install-hook-cert-manager-role
  namespace: {{ .Values.certManager.namespace }}-operator
rules:
- apiGroups:
  - operators.coreos.com 
  resources:
  - subscriptions
  - installplans
  verbs:
  - get
  - list
  - watch
