apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: post-install-hook-cert-manager
  namespace: {{ .Values.certManager.namespace }}-operator
  annotations:
    "helm.sh/hook": post-install
spec:
  backoffLimit: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/bash
        - /scripts/run.sh
        # image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        image: docker.io/bitnami/kubectl
        name: post-install
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        resources: {}
      volumes:
        - name: script-volume
          configMap:
            name: post-install-hook
      serviceAccount: post-install-hook-cert-manager
      restartPolicy: OnFailure
status: {}
