apiVersion: v1
data:
  "run.sh": |
    #/bin/bash
    set -xe
    kubectl wait --for=jsonpath={.status.installPlanRef.name} subscription openshift-cert-manager-operator --timeout=10s
    ip=$(kubectl get subscription openshift-cert-manager-operator -o=jsonpath={.status.installPlanRef.name})
    kubectl wait --for=condition=Installed installplan ${ip} --timeout=60s
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: post-install-hook
  namespace: {{ .Values.certManager.namespace }}-operator
