{{ if eq .Values.tools.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-config
  namespace: {{ .Values.kuadrant.namespace }}
type: Opaque
data:
  # It is redis://dragonfly.tools.svc.cluster.local:6379
  URL: "cmVkaXM6Ly9kcmFnb25mbHkudG9vbHMuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ=="
{{- end }}
