{{if and (eq .Values.istio.istioProvider "ossm3") (ne .Values.operatorName "authorino-operator") }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.istio.operatorNamespace }}
spec: {}
{{end}}
