{{if and (eq .Values.istio.istioProvider "ossm3") (ne .Values.kuadrant.operatorName "authorino-operator") }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: istio-system-operator
  namespace: {{ .Values.istio.operatorNamespace }}
spec:
  upgradeStrategy: Default
{{end}}
