{{ if .Values.tools.valkey.enable }}
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: {{ .Values.tools.namespace }}
  labels:
    app: valkey
spec:
  selector:
    app: valkey
  ports:
    - name: valkey
      port: 6379
      protocol: TCP
  type: LoadBalancer
{{end}}
