{{if and (eq .Values.istio.istioProvider "ossm3") (ne .Values.kuadrant.operatorName "authorino-operator") }}
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: {{ .Values.istio.namespace }}
  values:
    pilot:
      autoscaleMin: 2
  version: {{ .Values.istio.ossm3.version }}
{{end}}
