{{if and (eq .Values.istio.istioProvider "ossm3") (ne .Values.kuadrant.operatorName "authorino-operator") }}
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
spec:
  namespace: {{ .Values.istio.cniNamespace }}
  version: {{ .Values.istio.ossm3.version }}
{{end}}
