{{ if and .Values.tools.coredns.enable .Values.tools.coredns.autoDelegate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-install-autodelegate-sa
  namespace: {{ .Values.tools.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: post-install-autodelegate-role
  namespace: {{ .Values.tools.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: post-install-autodelegate-rb
  namespace: {{ .Values.tools.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: post-install-autodelegate-role
subjects:
  - kind: ServiceAccount
    name: post-install-autodelegate-sa
    namespace: {{ .Values.tools.namespace }}
{{ end }}
