{{- if .Values.kuadrant.indexImage }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kuadrant-upstream
  namespace: openshift-marketplace
spec:
  image: {{ .Values.kuadrant.indexImage }}
  sourceType: grpc
{{- end }}
