apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: {{ .Values.kuadrant.namespace }}
spec:
  name: {{ .Values.kuadrant.operatorName }}
  channel: {{ .Values.kuadrant.channel }}
  installPlanApproval: {{ .Values.kuadrant.installPlanApproval }}
{{- if eq .Values.kuadrant.installPlanApproval "Manual" }}
  startingCSV: {{ .Values.kuadrant.startingCSV }}
{{- end }}
{{- if .Values.kuadrant.indexImage }}
  source: kuadrant-upstream
  sourceNamespace: {{ .Values.kuadrant.namespace }}
{{- else }}
  source: {{ .Values.kuadrant.catalogSource }}
  sourceNamespace: {{ .Values.kuadrant.catalogSourceNamespace }}
{{- end }}
  config:
    env:
      - name: "AUTH_SERVICE_TIMEOUT"
        value: "1000ms"
{{- if eq .Values.istio.istioProvider "ocp"}}
      - name: "ISTIO_GATEWAY_CONTROLLER_NAMES"
        value: "openshift.io/gateway-controller/v1"
{{- end}}
