apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: {{ .Values.kuadrant.namespace }}
spec:
  channel: {{ .Values.kuadrant.channel }}
  installPlanApproval: Automatic
  name: kuadrant-operator
{{- if .Values.kuadrant.indexImage }}
  source: kuadrant-upstream
{{- else }}
  source: community-operators
{{- end }}
  sourceNamespace: openshift-marketplace
