{{ if and .Values.coredns.enable .Values.coredns.autoDelegate .Values.tools.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: coredns-credentials
  namespace: kuadrant
  annotations:
    base_domain: {{ first .Values.coredns.zones | trimSuffix "." }}
type: kuadrant.io/coredns
stringData:
  ZONES: {{ .Values.coredns.zones | join "," | trimSuffix "." | quote }}
{{ end }}
