{{ if .Values.tools.keycloak.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: credential-sso
  namespace: {{ .Values.tools.namespace }}
type: Opaque
stringData:
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: {{ randAlphaNum 24 | quote }}
{{ end }}
