{{if and .Values.tools.enabled (ne .Values.kuadrant.operatorName "authorino-operator") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
{{end}}