{{if and .Values.tools.enabled (ne .Values.kuadrant.operatorName "authorino-operator") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kuadrant-qe-issuer
spec:
  ca:
    secretName: kuadrant-qe-ca
{{ end }}
