{{ if and (.Values.tools.keycloak.enable) (eq .Values.tools.keycloak.keycloakProvider "deployment") }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.tools.namespace }}
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: keycloak
      port: 8080
      protocol: TCP
      targetPort: auth
  type: LoadBalancer
{{ end }}
