{{ if .Values.tools.coredns.enable }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: coredns
  namespace: {{ .Values.tools.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns
rules:
  - apiGroups:
      - kuadrant.io
    resources:
      - dnsrecords
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kuadrant.io
    resources:
      - dnsrecords/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coredns
subjects:
  - kind: ServiceAccount
    name: coredns
    namespace: {{ .Values.tools.namespace }}
{{ end }}
