apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  namespace: {{ .Values.tools.namespace }}
spec:
  channel: {{ .Values.tools.keycloak.operator.channel }}
  installPlanApproval: {{ .Values.tools.keycloak.operator.installPlanApproval }}
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhbk-operator.{{ .Values.tools.keycloak.version }}
