name: Helm chart static analysis
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Check if linting is required
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Run linting
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config .github/ct.yaml
