name: Helm chart releases
on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - 'values-tools.yaml'
      - 'values.yaml'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Package Helm charts
        run: |
          mkdir .cr-release-packages
          helm package ./charts/* -d .cr-release-packages
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Copy chart to gh-pages
        run: |
          cp .cr-release-packages/* gh-pages/
      - name: Generate new index.yaml
        run: |
          cd gh-pages
          helm repo index . --merge index.yaml
      - name: Commit and push
        run: |
          cd gh-pages
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update helm charts (github action)"
          git push origin gh-pages
